version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - static_data:/static
    depends_on:
      - app-web
    ports:
      - "80:80"

  app-web:
      container_name: app-web
      build: ./
      hostname: app-web
      expose:
        - 8000
      volumes:
        - .:/app
        - static_data:/app/static
      restart: on-failure

volumes:
  static_data:
