version: '3'
services:
  app-web:
      container_name: app-web
      build: ./
      hostname: app-web
      ports:
      - "8000:8000"
      volumes:
        - .:/app
        - static_data:/app/static
      restart: on-failure
  
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./configs:/etc/nginx/conf.d:ro
      - ./certs:/etc/ssl/certs
      - static_data:/static
    depends_on:
      - app-web
    ports:
      - "80:80"

volumes:
  static_data:
